### PR TITLE
Resolve #51 [Assert] Create "instanceOf" throwable matcher

### LINKED ISSUE #50: [Assert] Create "unexpected" throwable matcher
Implement a matcher that will check that actual throwable is `null`. Otherwise it shall produce a result with obvious message, like "No exception was expected".

Also implement factory method `#unexpected` in the `UberMatchers`
# 

Related to: #29
Blocked by: #35

### LINKED ISSUE #51: [Assert] Create "instanceOf" throwable matcher
Implement a matcher that will check that actual throwable is instance of the specified `Class<? extends Throwable>` type. Otherwise it shall produce obvious result, like "Unexpected exception", where:
- Actual = class of the actual value
- Expected = specified class
- Cause = actual throwable

**Note:** in case of actual `null` - matcher shall produce message "Expected exception not happened"

**Note:** in case of expected `null` - matcher shall check if actual is also `null` - otherwise it shall produce message "Unexpected exception"

Also implement factory method `#instanceOf(Class<? extends Throwable>)` in the `UberMatchers`
# 

Related to: #29
Blocked by: #35

### PR DESCRIPTION
**Pull request by zuzunker**
- Resolves #50 [Assert] Create "unexpected" throwable matcher
- Resolves #51 [Assert] Create "instanceOf" throwable matcher
1. ThrowableMatcher is implemented.
2. AssertBuilder is refactored to not replace cause.
3. Try is refactored to use ThrowableMatcher.
# 

Blocked by: #56

### CODE REVIEW

File: src/main/java/org/whaka/asserts/UberMatchers.java [hunk 1]
```diff
@@ -9,4 +13,24 @@
...
+	
+	/**
+	 * Create a matcher that will check that an exception is <code>null</code>.
+	 * And will set asserted throwable as cause of the result.
+	 * 
+	 * @see ThrowableMatcher
+	 */
+	public static Matcher<Throwable> notExpected() {
+		return ThrowableMatcher.notExpected();
+	}
```
Comment (visitorus) [inline src/main/java/org/whaka/asserts/UberMatchers.java:35]: This method seems redundant.

**Comment by zuzunker** [comment]
> This method seems redundant.

Classes `UberMatchers` and `NumberMatchers` are initially were planned as front-factory kind of class, for fast and easy access. Also it should be more convinient for those who worked with Hamcrest previously, since it has class `Matchers` with the same kind of factory methods.
